# select the docker 
version: '3.1'

services:
  mongodb:
    image: mongo:4.4
    container_name: db
    restart: always
    ports:
      - "27017:27017"

  my-node-app:
    image: jemseekings/tech230-james-app:latest
    container_name: app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb://mongodb:27017/posts
    command: >
      sh -c "npm install && npm start"
  